<a href="https://colab.research.google.com/github/gaurav31120/Machine-Learning/blob/main/Important%20Python%20Libraries/3_1_Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Numpy - Numerical Python - It is a python library

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0009993619999999481


Time taken by numpy array

In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0019905429999997892


Time taken by numpy array is 5-10% less than list

Numpy Arrays

In [5]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Note: In list output list are seperated by comma But in numpy array output list are not seperated by comma

shape - tell about the dimension of the array ----rows and cols

In [7]:
#creating a 1dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [13]:
# create a numpy array of Zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.31481036 0.86870349 0.90251645 0.28514278]
 [0.74022753 0.91587018 0.24435879 0.69999012]
 [0.40653836 0.95073793 0.85001141 0.50071885]]


In [20]:
# random integer values array in a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[10 52 83 66 97]
 [69 68 84 27 69]
 [92 99 12 62 77]]


In [21]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [22]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [24]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [25]:
c = np.random.randint(10,90,(5,5))
print(c)

[[31 27 27 71 60]
 [29 39 57 47 10]
 [10 83 10 40 31]
 [85 38 66 40 65]
 [28 38 27 84 69]]


In [26]:
# array dimension
print(c.shape)

(5, 5)


In [27]:
# number of dimensions
print(c.ndim)

2


In [28]:
# checking the number of elements in the array
print(c.size)

25


In [29]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [30]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatanate or joins two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [32]:
print(a)
print(b)

[[0 8 0]
 [4 2 6]
 [4 6 4]]
[[10 17 15]
 [13 14 13]
 [16 13 17]]


In [35]:
# here element wise operation will be done
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[10 25 15]
 [17 16 19]
 [20 19 21]]
[[-10  -9 -15]
 [ -9 -12  -7]
 [-12  -7 -13]]
[[  0 136   0]
 [ 52  28  78]
 [ 64  78  68]]
[[0.         0.47058824 0.        ]
 [0.30769231 0.14285714 0.46153846]
 [0.25       0.46153846 0.23529412]]


In [36]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [37]:
print(a)
print(b)

[[3 5 9]
 [6 4 1]
 [6 4 7]]
[[14 19 10]
 [15 17 12]
 [19 12 18]]


In [38]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 24 19]
 [21 21 13]
 [25 16 25]]
[[-11 -14  -1]
 [ -9 -13 -11]
 [-13  -8 -11]]
[[ 42  95  90]
 [ 90  68  12]
 [114  48 126]]
[[0.21428571 0.26315789 0.9       ]
 [0.4        0.23529412 0.08333333]
 [0.31578947 0.33333333 0.38888889]]


Array manipulation

In [39]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 4 1]
 [3 3 2]]
(2, 3)


In [40]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 3]
 [4 3]
 [1 2]]
(3, 2)


In [41]:
trans2 = array.T
print(trans)
print(trans.shape)

[[3 3]
 [4 3]
 [1 2]]
(3, 2)


In [42]:
# reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 1 1]
 [4 3 0]]
(2, 3)


In [43]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 1]
 [1 4]
 [3 0]]
(3, 2)
